"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../generated-wrappers/dummy_erc20_token"));
__export(require("../generated-wrappers/dummy_multiple_return_erc20_token"));
__export(require("../generated-wrappers/dummy_no_return_erc20_token"));
__export(require("../generated-wrappers/erc20_token"));
__export(require("../generated-wrappers/i_erc20_token"));
__export(require("../generated-wrappers/i_ether_token"));
__export(require("../generated-wrappers/mintable_erc20_token"));
__export(require("../generated-wrappers/unlimited_allowance_erc20_token"));
__export(require("../generated-wrappers/weth9"));
__export(require("../generated-wrappers/zrx_token"));
//# sourceMappingURL=wrappers.js.map