"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../generated-wrappers/dummy_erc1155_receiver"));
__export(require("../generated-wrappers/erc1155"));
__export(require("../generated-wrappers/erc1155_mintable"));
__export(require("../generated-wrappers/i_erc1155_mintable"));
__export(require("../generated-wrappers/i_erc1155_receiver"));
__export(require("../generated-wrappers/ierc1155"));
__export(require("../generated-wrappers/m_non_fungible_token"));
__export(require("../generated-wrappers/mixin_non_fungible_token"));
//# sourceMappingURL=wrappers.js.map