"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../generated-wrappers/exchange"));
__export(require("../generated-wrappers/exchange_wrapper"));
__export(require("../generated-wrappers/i_asset_proxy_dispatcher"));
__export(require("../generated-wrappers/i_exchange"));
__export(require("../generated-wrappers/i_exchange_core"));
__export(require("../generated-wrappers/i_match_orders"));
__export(require("../generated-wrappers/i_signature_validator"));
__export(require("../generated-wrappers/i_transactions"));
__export(require("../generated-wrappers/i_validator"));
__export(require("../generated-wrappers/i_wallet"));
__export(require("../generated-wrappers/i_wrapper_functions"));
__export(require("../generated-wrappers/reentrant_erc20_token"));
__export(require("../generated-wrappers/test_asset_proxy_dispatcher"));
__export(require("../generated-wrappers/test_exchange_internals"));
__export(require("../generated-wrappers/test_signature_validator"));
__export(require("../generated-wrappers/test_static_call_receiver"));
__export(require("../generated-wrappers/validator"));
__export(require("../generated-wrappers/wallet"));
__export(require("../generated-wrappers/whitelist"));
//# sourceMappingURL=wrappers.js.map