"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../generated-wrappers/erc1155_proxy"));
__export(require("../generated-wrappers/erc20_proxy"));
__export(require("../generated-wrappers/erc721_proxy"));
__export(require("../generated-wrappers/i_asset_data"));
__export(require("../generated-wrappers/i_asset_proxy"));
__export(require("../generated-wrappers/i_authorizable"));
__export(require("../generated-wrappers/mixin_authorizable"));
__export(require("../generated-wrappers/multi_asset_proxy"));
__export(require("../generated-wrappers/static_call_proxy"));
__export(require("../generated-wrappers/test_static_call_target"));
//# sourceMappingURL=wrappers.js.map